### ISSUE TITLE
General refactoring efforts

### ISSUE THREAD

**Issue by rieckpil** [stratospheric-dev/stratospheric#48]
A list of possible refactoring efforts we can tackle:

- add a type-safe definition of our custom properties with a `StratosphericProperties` class to define the properties like:

```yaml
stratospheric:
  registration:
    invite-codes: ABC
  collaboration:
    auto-confirm: false
    sharing-queue:
    web-socket-relay-endpoint:
   ...
```

instead of 

```yaml
custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC # TODO: outsource them -> e.g. env variable or database
  sharing-queue: stratospheric-todo-sharing
  external-url: https://app.stratospheric.dev
  auto-confirm-collaborations: false
  breadcrumb-table-name: breadcrumbs
```

- Upgrade to https://github.com/awspring/spring-cloud-aws to simplify e.g. the setup for testing, better convenient defaults
- Don't rely on Spring profiles to toggle on/off behavior (https://reflectoring.io/dont-use-spring-profile-annotation/) and rather use property values

As some of these refactorings will change code examples and explanations in the book, we should organize such refactoring efforts and do them once the book is content-complete.
